sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
      # - oracle-java10-installer

language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  # - oraclejdk10
