version: "{build}"
image: Visual Studio 2017

skip_tags: true

build:
  verbosity: detailed

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk10

build_script:
  - mvnw.cmd clean install -DskipTests=true

test_script:
  - mvnw.cmd verify

cache:
  -  C:\Users\appveyor\.m2\ -> pom.xml
